from g2p_en import G2p
from difflib import SequenceMatcher
import nltk
nltk.download('averaged_perceptron_tagger_eng')

g2p = G2p()

def pronunciation_score(transcript, expected_transcript):
    #both transcripts will be translated phonemically.
    #the expected transcript should aready be broken down and formatted correctly in a json file.
    #for the scoring process each section of the breakdown will compared to each other and the code should keep track of how many chunks match
    #everytime a chunk does not match the score will decrease. 
    #if there is time; implement a way for the app to keep track of what chunks were incorrect and incorporate suggestions on how to improve in the feedback when working with gemini

    #maybe disregard this or keep for simplicity/testing
    #if (transcript != expected_pronunciation):
        #"Try again!"

    #scoring output will be expected_pronunciation, detected_pronunciation, matched_chunks, confidence (similar layout as prototype; but not visible to user after testing)

    #transcript comes from frontend sending recording
    #expected_transcript comes from wordbank generated by gemini

    detected_phonemes = g2p(transcript)
    expected_phonemes = g2p(expected_transcript)

    matched_phonemes = SequenceMatcher(None, detected_phonemes, expected_phonemes)
    score = matched_phonemes.ratio()
    print("score calculated...")

    return {
        "detected_pronunciation": detected_phonemes,
        "expected_pronunciation": expected_phonemes,
        "confidence": score
    }